apiVersion: v1
kind: Service
metadata:
  name: {{ include "bifrost.fullname" . }}-portal
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: portal
  ports:
    - name: http
      port: 80
      targetPort: http
