{{- if and .Values.signingKey.value (not .Values.signingKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bifrost.fullname" . }}-signing
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.signingKey.key }}: {{ .Values.signingKey.value | quote }}
{{- end }}
