//! Agent instructions for migrated repos (#243).
//!
//! When a converted workflow is delivered, the target repo benefits from a
//! `.github/copilot-instructions.md` / `AGENTS.md` so an agent (the Copilot
//! coding agent, or any IDE agent) working on it knows it was migrated from
//! Azure DevOps, what manual setup it depends on, and the rules to follow —
//! grounded in the audit, not generic boilerplate. Deterministic; no LLM.

use crate::audit::ManualTaskKind;
use crate::model::Portfolio;

/// Generate the Markdown for `.github/copilot-instructions.md`, grounded in the
/// portfolio's audit (secrets to set, connections to federate, the allow-list,
/// the gap-filled steps). Safe on an empty audit (emits the conventions only).
pub fn agent_instructions(portfolio: &Portfolio) -> String {
    let a = &portfolio.audit;
    let mut s = String::new();

    s.push_str("# Agent instructions\n\n");
    s.push_str(
        "These GitHub Actions workflows were migrated from Azure DevOps by Bifrost. Gaps the \
         Importer could not convert were filled from the diff by a model and reviewed by a human. \
         This file is context for an agent working in this repo.\n\n",
    );

    s.push_str("## Conventions\n\n");
    s.push_str(
        "- Workflows live in `.github/workflows/`. Triggers use `on:`; jobs use `runs-on:`.\n",
    );
    s.push_str(
        "- Secrets are GitHub Actions secrets (`${{ secrets.NAME }}`) — never commit values.\n",
    );
    s.push_str("- Pin third-party actions to a commit SHA.\n\n");

    s.push_str("## When you change a workflow here\n\n");
    s.push_str("- Do not reintroduce Azure DevOps constructs (ADO tasks, `$(var)` macros, service connections).\n");
    s.push_str("- Preserve the required setup below — these workflows depend on it.\n");
    s.push_str("- Review-first: open a pull request; never push converted CI straight to the default branch.\n");
    s.push_str("- Risk and cost are computed deterministically by Bifrost — do not have a model score or price them.\n\n");

    // Secrets (names only — values are never read).
    let secrets: Vec<&str> = a
        .manual_tasks
        .iter()
        .filter(|m| m.kind == ManualTaskKind::Secret)
        .map(|m| m.name.as_str())
        .collect();
    if !secrets.is_empty() {
        s.push_str("## Secrets to create (names only — set the values in GitHub)\n\n");
        for name in secrets {
            s.push_str(&format!("- `{name}`\n"));
        }
        s.push('\n');
    }

    // Self-hosted runners.
    let runners: Vec<&str> = a
        .manual_tasks
        .iter()
        .filter(|m| m.kind == ManualTaskKind::SelfHostedRunner)
        .map(|m| m.name.as_str())
        .collect();
    if !runners.is_empty() {
        s.push_str("## Self-hosted runners to provision\n\n");
        for name in runners {
            s.push_str(&format!(
                "- `{name}` — match the label the workflow expects.\n"
            ));
        }
        s.push('\n');
    }

    // Service connections → OIDC.
    if !a.service_connections.is_empty() {
        s.push_str("## Service connections to recreate (OIDC / Entra federation)\n\n");
        for c in &a.service_connections {
            s.push_str(&format!("- `{}` ({})\n", c.name, c.kind));
        }
        s.push('\n');
    }

    // Actions allow-list.
    if !a.actions.is_empty() {
        s.push_str("## Actions used (add to the org allow-list)\n\n");
        for action in &a.actions {
            s.push_str(&format!("- `{action}`\n"));
        }
        s.push('\n');
    }

    // Gap-filled / unsupported steps.
    if !a.unsupported_steps.is_empty() {
        s.push_str("## Gap-filled steps to double-check\n\n");
        s.push_str("The Importer could not convert these; the model filled them and a human reviewed — verify they behave as intended:\n\n");
        for u in &a.unsupported_steps {
            s.push_str(&format!("- `{}` (x{})\n", u.task, u.count));
        }
        s.push('\n');
    }

    s.push_str("---\n\n");
    s.push_str("Generated by Bifrost. We wrap the official GitHub migration tools and never reimplement their conversion logic.\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::audit::{ManualTask, UnsupportedStep};
    use crate::ingestion::ServiceConnection;
    use crate::model::{Portfolio, PortfolioAudit, PortfolioSummary, PortfolioTotals};

    fn portfolio(audit: PortfolioAudit) -> Portfolio {
        Portfolio {
            summary: PortfolioSummary {
                org: "o".into(),
                importer_version: "v".into(),
                importer_image_digest: String::new(),
                ado2gh_version: "n/a".into(),
                air_gap: false,
                generated_at: "t".into(),
                totals: PortfolioTotals {
                    pipelines: 0,
                    orgs: 1,
                    projects: 0,
                    yaml: 0,
                    classic: 0,
                    green: 0,
                    amber: 0,
                    red: 0,
                    forecast_minutes: 0,
                },
            },
            pipelines: vec![],
            audit,
        }
    }

    #[test]
    fn always_emits_conventions_and_review_first() {
        let md = agent_instructions(&portfolio(PortfolioAudit::default()));
        assert!(md.contains("# Agent instructions"));
        assert!(md.contains("Review-first"));
        assert!(md.contains(".github/workflows/"));
    }

    #[test]
    fn grounds_in_the_audit() {
        let audit = PortfolioAudit {
            manual_tasks: vec![ManualTask {
                kind: ManualTaskKind::Secret,
                name: "NUGET_API_KEY".into(),
            }],
            unsupported_steps: vec![UnsupportedStep {
                task: "DownloadSecureFile@1".into(),
                count: 2,
            }],
            actions: vec!["actions/checkout@v4".into()],
            service_connections: vec![ServiceConnection {
                id: "1".into(),
                name: "azure-prod".into(),
                kind: "azurerm".into(),
                project: "P".into(),
            }],
            variable_groups: vec![],
        };
        let md = agent_instructions(&portfolio(audit));
        assert!(md.contains("NUGET_API_KEY"));
        assert!(md.contains("azure-prod"));
        assert!(md.contains("actions/checkout@v4"));
        assert!(md.contains("DownloadSecureFile@1"));
    }
}
